apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-tile-changer
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: tile-changer
    http:
      paths:
      - path: /
        backend:
          serviceName: svc-nginx-tile-changer
          servicePort: 80
  - host: tile-changer
    http:
      paths:
      - path: /mapea5/
        backend:
          serviceName: svc-mapea-tile-changer
          servicePort: 8080